CREATE TABLE IF NOT EXISTS statistic
(
    request_id INT GENERATED BY DEFAULT AS IDENTITY,
    app        VARCHAR(255) NOT NULL,
    uri        VARCHAR(255) NOT NULL,
    ip         VARCHAR(15)  NOT NULL,
    timestamp  TIMESTAMP,
    CONSTRAINT pk_statistic PRIMARY KEY (request_id)
);
