-- drop table if exists statistic cascade;

CREATE TABLE IF NOT EXISTS statistic
(
    request_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        VARCHAR(64)                          NOT NULL,
    uri        VARCHAR(64)                          NOT NULL,
    ip         VARCHAR(16)                          NOT NULL,
    timestamp  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_statistic PRIMARY KEY (request_id)
);
